# Generated by Django 3.1.7 on 2021-05-16 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210516_2100'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='dosen',
            new_name='description',
        ),
    ]
